experiment:
  name: mistral_7b_vanilla
  models:
    - name: mistralai/Mistral-7B-Instruct-v0.3
      mode: vllm
      max_completion_tokens: 4096

  dataset_groups:
    - wmt_all
    - synthetic_all
  methods:
    - type: json
      name: json

    - type: json
      name: json_structured
      use_structured_outputs: true

    - type: json_occurrence
      name: json_occurrence

    - type: json_occurrence
      name: json_occurrence_structured
      use_structured_outputs: true

    - type: xml
      name: xml

    - type: index
      name: index

    - type: index
      name: index_enriched
      enrich_prompt: true

  seeds: [42, 43, 44, 45, 46]

slurm:
  job_name: exp_Mistral-7B
  num_gpus: 1
  time: "48:00:00"

providers:
  vllm:
    model: mistralai/Mistral-7B-Instruct-v0.3
    tensor_parallel_size: 1
    max_model_len: 8192

env:
  cuda_home: /opt/cuda/12.3
  hf_home: /lnet/troja/work/people/<your_username>/.cache/huggingface

project:
  dir: /home/<your_username>/personal_work_ms/span_labeling
  run_script: span_labeling/experiments/run.py
  max_concurrent_requests: 8
