experiment:
  name: gpt_5_mini_vanilla
  models:
    - name: gpt-5-mini
      mode: openai
      max_completion_tokens: 4096

  dataset_groups:
    - wmt_all
    - synthetic_all
  methods:
    - type: json
      name: json

    - type: json
      name: json_structured
      use_structured_outputs: true

    - type: json_occurrence
      name: json_occurrence

    - type: json_occurrence
      name: json_occurrence_structured
      use_structured_outputs: true

    - type: xml
      name: xml

    - type: index
      name: index

    - type: index
      name: index_enriched
      enrich_prompt: true

  # seeds: [42, 43, 44, 45, 46]
  seeds: [42]


slurm:
  job_name: exp_gpt_5_mini

project:
  dir: /home/semin/personal_work_ms/span_labeling
  run_script: span_labeling/experiments/run.py
  max_concurrent_requests: 8
